#!/bin/bash -ex

PLAYLIST_ID="$1"
AUTH_TOKEN="$2"

while IFS= read -r TRACK_ID; do
    echo "Text read from file: $TRACK_ID"
    URL="https://api.spotify.com/v1/playlists/${PLAYLIST_ID}/tracks?uris=spotify%3Atrack%3A${TRACK_ID}"
    curl -X "POST" ${URL} -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer ${AUTH_TOKEN}"
done < tracks_to_add.txt

