#!/bin/bash

PLAYLIST_ID="$1"
AUTH_TOKEN="$2"
URL="https://api.spotify.com/v1/playlists/${PLAYLIST_ID}/tracks"
PWD=`pwd`
TEMP_FILE="${PWD}/tmp.json"
EXISTING_IDS="${PWD}/existing_ids.txt"

function get_tracks() {
    # this will get you a list of all tracks that are currently in a playlist
    curl --write-out -i -X "GET" $URL -H "Authorization: Bearer $AUTH_TOKEN" -o ${TEMP_FILE}
    #curl --write-out -i -X "GET" $URL -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTH_TOKEN" -o ${TEMP_FILE}
    URL=`cat ${TEMP_FILE} | jq -r '.next'`
    cat ${TEMP_FILE} | jq -r '.items[].track | select(.type == "track") | .id' >> existing_ids.txt

}

get_tracks
while ! [[ "$URL" == "null" ]]; do
    get_tracks
done

